const prisma = require('../src/db/prisma')


async function main() {
    const warga = await prisma.warga.findMany({ where: { NOT: { wargaId: 0 } } })
    const jenisUmkmMakanan = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Makanan" } })
    const jenisUmkmJasa = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Jasa" } })
    const jenisUmkmPerdagangan = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Perdagangan" } })
    const jenisUmkmKerajinan = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Kerajinan" } })
    const jenisUmkmOtomotif = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Otomotif" } })
    const jenisUmkmFashion = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Fashion" } })
    const jenisUmkmMinuman = await prisma.jenisUmkm.findFirst({ where: { namaJenisUmkm: "Minuman" } })

    const wargaId = () => warga[Math.floor(Math.random() * warga.length)].wargaId
    
    const dataUmkm = [
        {
            nama: "Pempek 77 Palembang",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Mataram No.28, Rejowinangun Utara, Kec. Magelang Tengah, Kota Magelang, Jawa Tengah 56214",
            latitude: -7.478299202671914,
            longitude: 110.21972251500817,
            wargaId: wargaId(),
            deskripsi: "BARU DI JALAN IKHLAS, SPOT JAJAN PEMPEK 77 LEGEND PELOPOR PEMPEK PALEMBANG DI MAGELANG, CUKO RACIK SENDIRI MANIS & PEDAS 😍🤩",
            approve: true,
            status: true,
        },
        {
            nama: "Koki Kita",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Pahlawan No.125, Potrobangsan, Kec. Magelang Utara, Kota Magelang, Jawa Tengah 56116",
            latitude: -7.452752960084105,
            longitude: 110.22143887158512,
            wargaId: wargaId(),
            deskripsi: "Rayakan setiap momen istimewa dengan nasi kotak dari Koki Kita!\n\n📦 Pilihan menu variatif, harga ramah kantong, dan kualitas terbaik.\n\nPesan sekarang untuk berbagai acara spesial Anda!",
            approve: true,
            status: true,
        },
        {
            nama: "Nyokelat",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMinuman.jenisUmkmId,
            lokasi: "C75H+59M, Gn. Pring, Gunungpring, Kec. Muntilan, Kabupaten Magelang, Jawa Tengah 56415",
            latitude: -7.536813890235534,
            longitude: 110.16616365214078,
            deskripsi: "Cokelat lembut dan empuk yang langsung melted di mulut dengan rasa Salted Caramel yang enak banget ada sensasi caramel dan guruh dr seasaltnya dan dicover dengan bittersweet dari cocoa powder",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Toko Kue Maher",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Krombangan, Sanggaran, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah 56172",
            latitude: -7.559288245885016,
            longitude: 110.21044226888604,
            deskripsi: "Maher snack cookies n tart Maher\nTerima pesanan kue ulang tahun",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Rumah Jahit DANISH",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmJasa.jenisUmkmId,
            lokasi: "Japunan, Sraten, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah 56172",
            latitude: -7.55336,
            longitude: 110.21839,
            deskripsi: "Menerima pesanan jahitan kaos, t-shirt, kaos olahraga, sweater, souvenir, dan lain-lain.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Mie Ayam Dan Bakso Pak Pe",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Citran, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah 56172",
            latitude: -7.55336,
            longitude: 110.21839,
            deskripsi: "Sedia berbagai jenis makanan/minuman seperti bakmie, soto, bakso, dan sop.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Barokah Buah",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmPerdagangan.jenisUmkmId,
            lokasi: "Sraten, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah 56172",
            latitude: -7.55336,
            longitude: 110.21839,
            deskripsi: "Menjual berbagai macam buah-buahan segar.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Toko Bu Etik",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmPerdagangan.jenisUmkmId,
            lokasi: "Sraten, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah 56172",
            latitude: -7.55336,
            longitude: 110.21839,
            deskripsi: "Menjual Pakaian anak, pakaian dewasa, seragam sekolah, sepatu, dan alat tulis.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Getuk Mbok'e",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipO3j4J3B_xH2Xl3f2y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Dusun Bletukan, Desa Kalinegoro, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah",
            latitude: -7.52,
            longitude: 110.23,
            deskripsi: "Getuk, makanan khas Magelang. Oleh-oleh legendaris.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Sabila Craft",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmKerajinan.jenisUmkmId,
            lokasi: "Desa Sumberrejo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah",
            latitude: -7.51,
            longitude: 110.22,
            deskripsi: "Kerajinan tangan dari bahan kulit kerang. Unik dan artistik.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Joglo Tanjung",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Tanjung, Bulurejo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah",
            latitude: -7.505,
            longitude: 110.225,
            deskripsi: "Restoran bergaya tradisional Jawa dengan aneka kuliner khas.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Bengkel Motor Pak Man",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmOtomotif.jenisUmkmId,
            lokasi: "Jl. Raya Kalinegoro, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah",
            latitude: -7.555,
            longitude: 110.217,
            deskripsi: "Servis motor, ganti oli, dan tambal ban. Pelayanan cepat dan ramah.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Ayam Goreng Bu Ranti",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Mayor Unus, Donorojo, Kec. Mertoyudan, Kabupaten Magelang, Jawa Tengah",
            latitude: -7.558,
            longitude: 110.211,
            deskripsi: "Ayam goreng kampung dengan sambal khas yang pedas mantap.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Toko Besi & Bangunan Sido Muncul",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmPerdagangan.jenisUmkmId,
            lokasi: "Jl. Magelang - Purworejo, Kalinegoro, Kec. Mertoyudan, Kabupaten Magelang",
            latitude: -7.53,
            longitude: 110.22,
            deskripsi: "Menyediakan berbagai macam bahan bangunan dan alat pertukangan.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Bakso Balungan Pak Granat",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Jenggolo, Kemirirejo, Kec. Magelang Tengah, Kota Magelang, Jawa Tengah",
            latitude: -7.48,
            longitude: 110.22,
            deskripsi: "Bakso balungan sapi dengan kuah kaldu yang gurih dan kaya rempah.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Sate Kambing Muda Pak Budi",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Tentara Pelajar, Cacaban, Kec. Magelang Tengah, Kota Magelang, Jawa Tengah",
            latitude: -7.47,
            longitude: 110.21,
            deskripsi: "Sate kambing muda empuk dengan bumbu kecap dan irisan bawang merah.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Gudeg Yu Djum",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Mayjend Bambang Soegeng, Saratan, Sumberrejo, Kec. Mertoyudan",
            latitude: -7.50,
            longitude: 110.22,
            deskripsi: "Gudeg legendaris dengan rasa manis dan gurih yang khas.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Bebek Goreng H. Slamet",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Raya Secang - Magelang, Banyakan, Mertoyudan, Kabupaten Magelang",
            latitude: -7.49,
            longitude: 110.22,
            deskripsi: "Bebek goreng empuk dengan sambal korek yang super pedas.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Warung Kopi Klotok",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMinuman.jenisUmkmId,
            lokasi: "Jl. Kaliurang, Pakem, Sleman (dekat Magelang)",
            latitude: -7.60,
            longitude: 110.42,
            deskripsi: "Warung kopi dengan suasana pedesaan yang asri dan menu ndeso.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Angkringan Gajah",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Kaliurang, Sleman (dekat Magelang)",
            latitude: -7.62,
            longitude: 110.43,
            deskripsi: "Angkringan modern dengan berbagai pilihan sego kucing dan sate.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "House of Raminten",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. FM Noto No.7, Kotabaru, Yogyakarta (populer di kalangan wisatawan Magelang)",
            latitude: -7.78,
            longitude: 110.37,
            deskripsi: "Restoran unik dengan konsep angkringan modern dan nuansa Jawa yang kental.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "JeJamuran",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Pramuka No.53, Niron, Pandowoharjo, Sleman (populer di kalangan wisatawan Magelang)",
            latitude: -7.68,
            longitude: 110.35,
            deskripsi: "Restoran dengan berbagai olahan jamur yang lezat dan inovatif.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Mangut Lele Mbah Marto",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Parangtritis, Sewon, Bantul (populer di kalangan wisatawan Magelang)",
            latitude: -7.85,
            longitude: 110.37,
            deskripsi: "Mangut lele legendaris dengan kuah santan pedas yang khas.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Sate Klathak Pak Pong",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Sultan Agung, Jejeran, Wonokromo, Pleret, Bantul (populer di kalangan wisatawan Magelang)",
            latitude: -7.86,
            longitude: 110.40,
            deskripsi: "Sate kambing yang ditusuk dengan jeruji besi sepeda, disajikan dengan kuah gulai.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Klinik Kopi",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMinuman.jenisUmkmId,
            lokasi: "Jl. Kaliurang KM 7.8, Gang Bima, Sinduharjo, Ngaglik, Sleman (populer di kalangan wisatawan Magelang)",
            latitude: -7.73,
            longitude: 110.40,
            deskripsi: "Kedai kopi yang menyajikan kopi single origin dari berbagai daerah di Indonesia.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Toko Oleh-Oleh Enting-Enting Gepuk",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmPerdagangan.jenisUmkmId,
            lokasi: "Jl. Jend. Sudirman, Magersari, Kec. Magelang Selatan, Kota Magelang",
            latitude: -7.49,
            longitude: 110.21,
            deskripsi: "Toko oleh-oleh khas Magelang yang menjual enting-enting gepuk dan makanan ringan lainnya.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Cuci Mobil & Motor Hidrolik 24 Jam",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmJasa.jenisUmkmId,
            lokasi: "Jl. Urip Sumoharjo, Wates, Kec. Magelang Utara, Kota Magelang",
            latitude: -7.46,
            longitude: 110.22,
            deskripsi: "Jasa cuci mobil dan motor dengan sistem hidrolik, buka 24 jam.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Fashion Outlet 'Gaya Kita'",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmFashion.jenisUmkmId,
            lokasi: "Jl. Pemuda, Kemirirejo, Kec. Magelang Tengah, Kota Magelang",
            latitude: -7.47,
            longitude: 110.21,
            deskripsi: "Toko pakaian dengan berbagai model terbaru untuk pria dan wanita.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Kerajinan Gerabah Kragilan",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmKerajinan.jenisUmkmId,
            lokasi: "Dusun Kragilan, Desa Donorojo, Kec. Mertoyudan, Kabupaten Magelang",
            latitude: -7.56,
            longitude: 110.20,
            deskripsi: "Pusat kerajinan gerabah dan genteng dengan berbagai macam produk.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        },
        {
            nama: "Tahu Pojok Magelang",
            gambar: "https://lh3.googleusercontent.com/p/AF1QipN4V8q3Z3n3e2Y2q5A2k6G-J5C6X2m3r1bY3w8=s1360-w1360-h1020",
            jenisUmkmId: jenisUmkmMakanan.jenisUmkmId,
            lokasi: "Jl. Tentara Pelajar No.Kav. 1, Cacaban, Kec. Magelang Tengah, Kota Magelang",
            latitude: -7.475,
            longitude: 110.215,
            deskripsi: "Kuliner legendaris Magelang, tahu dengan bumbu khas.",
            wargaId: wargaId(),
            approve: true,
            status: true,
        }
    ]
    for (const umkm of dataUmkm) {
        const check = await prisma.umkm.findFirst({ where: { nama: umkm.nama } })
        if (!check) {
            try {
                await prisma.umkm.create({ data: umkm })
                console.log(`Umkm ${umkm.nama} berhasil dibuat`);
            } catch (error) {
                console.log(error);
            }
        } else {
            console.log(`Umkm ${umkm.nama} sudah ada`);
        }
    }
}

main()