const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET
const CLOUDINARY_BERITA = 'di-desa/berita'
const CLOUDINARY_UMKM = 'di-desa/umkm'
const CLOUDINARY_PROFILE = 'di-desa/profile'
const CLOUDINARY_PENGADUAN = 'di-desa/pengaduan'


module.exports = {
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_BERITA,
    CLOUDINARY_UMKM,
    CLOUDINARY_PROFILE,
    CLOUDINARY_PENGADUAN
}